import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { chromium } from 'playwright';
import { createPreview } from '../server/preview.ts';
import { CareerService } from '../server/service.ts';
import { initialState } from '../src/demo.ts';
import { parseResearch } from '../server/schema.ts';

const data = await mkdtemp(join(tmpdir(), 'waypoint-ui-'));
const shots = resolve(process.env.SCREENSHOT_DIR || 'test-artifacts');
await mkdir(shots, { recursive: true });
const fakeResearch = async (_state, signal, event) => {
  event('Searching live vacancy sources.');
  event('Reviewing careers.acme.com.', { url: 'https://careers.acme.com/jobs/123', title: 'Senior Product Manager', status: 'reviewing', seenAt: new Date().toISOString() });
  await new Promise(r => setTimeout(r, 2200));
  if (signal.aborted) throw new Error('Research cancelled.');
  const d = initialState();
  return parseResearch({ summary: 'Integration test research, with a simulated provider.', families: d.families, questions: [], roles: d.roles.slice(0, 1).map(r => ({ ...r, demo: false, status: 'open', sources: [{ url: 'https://careers.acme.com/jobs/123', title: 'Test vacancy', excerpt: 'Lead a cross-functional product team.', checkedAt: '' }] })) });
};
const service = await new CareerService(data, false, fakeResearch).init();
const preview = await createPreview({ service, port: 0 });
const browser = await chromium.launch({
  headless: true,
  ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}),
  args: process.env.CHROMIUM_PATH ? ['--no-sandbox', '--in-process-gpu', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--single-process', '--no-zygote'] : [],
});
const errors = [];
let checks = 0;
const check = (value, description) => { assert.ok(value, description); checks++; console.log(`✓ ${description}`); };
try {
  const page = await browser.newPage({ viewport: { width: 1460, height: 1050 }, deviceScaleFactor: 1 });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`http://127.0.0.1:${preview.server.address().port}`);
  await page.waitForSelector('.role-card');
  check(await page.locator('.role-card').count() === 6, 'Demo is labelled and renders six illustrative opportunities');
  await page.screenshot({ animations: 'disabled', path: join(shots, 'waypoint-preview.png'), fullPage: true });
  await page.locator('[data-fit="adjacent"]').click();
  check(await page.locator('.role-card').count() === 3, 'Fit categories filter the list');
  await page.locator('#search').fill('Canopy');
  check(await page.locator('.role-card').count() === 1, 'Search narrows roles without losing input focus');
  await page.locator('[data-fit="all"]').click();
  await page.locator('#search').fill('');
  await page.locator('[data-action="filters"]').click();
  await page.locator('[name="mode"]').selectOption('Remote');
  await page.locator('#filter-form button[type="submit"]').click();
  check(await page.locator('.role-card').count() === 3, 'Work-arrangement filter applies');
  await page.locator('[data-action="clear-filters"]').click();
  const first = page.locator('.role-card').first();
  await first.locator('[data-save]').click();
  check(service.state.saved.length === 1, 'Shortlist changes persist through the service');
  await page.locator('.role-card').first().locator('.role-open').click();
  await page.locator('[data-detail-tab="evidence"]').click();
  check(await page.locator('.evidence-card').count() === 3, 'Requirement evidence and gaps are inspectable');
  await page.screenshot({ animations: 'disabled', path: join(shots, 'waypoint-evidence.png') });
  await page.locator('[data-feedback="more"]').click();
  check(service.state.feedback.length === 1, 'Feedback is recorded');
  await page.locator('[data-detail-tab="prepare"]').click();
  await page.locator('[name="notes"]').fill('Prepare the 24% activation example.');
  await page.locator('#application-form [name="stage"]').selectOption('Interview');
  await page.locator('#application-form button[type="submit"]').click();
  check(service.state.applications[0]?.stage === 'Interview', 'Application preparation and stage are saved');
  await page.keyboard.press('Escape');
  await page.locator('.nav-item[data-nav="applications"]').click();
  check(await page.locator('.application-card').count() === 1, 'Application appears on the pipeline');
  await page.reload();
  await page.waitForSelector('.role-card');
  check(service.state.applications[0].notes === 'Prepare the 24% activation example.', 'Application notes survive reload');
  await page.locator('[data-nav="paths"]').first().click();
  check(await page.locator('.path-card').count() === 4, 'Career paths expose adjacent and stretch directions');
  await page.screenshot({ animations: 'disabled', path: join(shots, 'waypoint-paths.png'), fullPage: true });
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.locator('[data-undo]').click();
  check(service.state.feedback.length === 0, 'Preference feedback can be undone');
  await page.locator('[data-action="new"]').first().click();
  await page.locator('[data-action="confirm-new"]').click();
  await page.waitForSelector('#profile-form');
  check(!service.state.demo && service.state.roles.length === 0, 'Creating a profile removes sample opportunities');
  await page.locator('[name="name"]').fill('Jamie Rivers');
  await page.locator('[name="location"]').fill('Manchester, UK');
  await page.locator('#cv-upload').setInputFiles({ name: 'cv.txt', mimeType: 'text/plain', buffer: Buffer.from('Product manager with six years of experience leading cross-functional teams, customer research and measurable improvements to onboarding. Led a team of eight and improved customer activation by 24 percent.') });
  await page.waitForFunction(() => document.querySelector('[name="background"]').value.includes('Product manager'));
  check((await page.locator('[name="background"]').inputValue()).includes('24 percent'), 'Local CV import fills a reviewable draft');
  await page.locator('[data-step="preferences"]').click();
  await page.locator('[name="ambitions"]').fill('Lead a climate product team and stay close to discovery.');
  await page.locator('[name="locations"]').fill('UK remote');
  await page.locator('[name="workAuthorization"]').fill('UK right to work, no sponsorship needed.');
  await page.locator('[data-action="save-profile"]').first().click();
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Profile saved'));
  check(service.state.profile.name === 'Jamie Rivers', 'Profile form preserves values across steps');
  await page.locator('.nav-item[data-nav="settings"]').click();
  await page.locator('#schedule-form [name="enabled"]').check();
  await page.locator('#schedule-form [name="time"]').fill('09:30');
  await page.locator('#schedule-form button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Daily research enabled'));
  check(service.state.settings.researchSchedule.enabled && service.state.settings.researchSchedule.time === '09:30', 'Scheduled research preferences persist');
  await page.locator('.nav-item[data-nav="research"]').click();
  await page.locator('[data-action="research"]').click();
  await page.waitForSelector('.live-source');
  check(await page.locator('.live-source').getAttribute('href') === 'https://careers.acme.com/jobs/123', 'Research shows the source currently being reviewed');
  await page.waitForSelector('.research-summary', { timeout: 12000 });
  check(service.state.runs[0].status === 'completed' && service.state.roles.length === 1, 'Research progress flows into sourced results (simulated AI provider)');
  await page.locator('.nav-item[data-nav="discover"]').click();
  await page.locator('.role-open').click();
  check(await page.locator('.source-link').count() === 1, 'Sourced research has a real link field and freshness context');
  await page.keyboard.press('Escape');
  await page.locator('.role-selector input').check();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-action="remove-selected"]').click();
  await page.waitForFunction(() => document.querySelectorAll('.role-card').length === 0);
  check(service.state.roles.length === 0, 'Selected opportunities can be removed with related workspace data');
  await page.setViewportSize({ width: 390, height: 844 });
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Narrow layout has no horizontal overflow');
  await page.screenshot({ animations: 'disabled', path: join(shots, 'waypoint-mobile.png'), fullPage: true });
  check(errors.length === 0, `No browser runtime errors: ${errors.join('; ')}`);
  console.log(`\n${checks} UI checks passed. Screenshots: ${shots}`);
} finally { await browser.close(); await preview.close(); await rm(data, { recursive: true, force: true }); }
